name: Propose Translations
on:
  workflow_dispatch:
    inputs:
      translations: # wait for dispatcher input for a langcode (xx-xx)
        type: string
        required: true

jobs:
  propose_translation:
    uses: openvoiceos/.github/.github/workflows/propose_translation.yml@feat/shared_actions1
    secrets: inherit
    with:
      action_branch: feat/shared_actions1
      python_version: "3.10"
      language: ${{ inputs.translations }}
      reviewers: "jarbasai,emphasize"
