name: skill_tests
on:
  pull_request: {}
  workflow_dispatch: {}
jobs:
  py_build_tests:
    name: py_build_tests
    permissions:
      contents: read
    uses: openvoiceos/.github/.github/workflows/python_build_tests.yml@feat/shared_actions1
    with:
      python_matrix: '[3.9, "3.10", "3.11"]'
  skill_unit_tests:
    name: skill_unit_tests
    permissions:
      contents: read
    uses: openvoiceos/.github/.github/workflows/pytest_file_or_dir.yml@feat/shared_actions1
    with:
      action_branch: feat/shared_actions1
      test_location: test
      python_matrix: '[3.9, "3.10", "3.11"]'
      is_skill: true
      upload_coverage: true
