name: skill_tests
on:
  pull_request: {}
  workflow_dispatch: {}
jobs:
  # skill_unit_tests:
  #   name: skill_unit_tests
  #   permissions:
  #     contents: read
  #   uses: neongeckocom/.github/.github/workflows/skill_tests.yml@master
  #   with:
  #     ovos_versions: '["3.10", "3.11"]'
  skill_unit_tests:
    name: skill_unit_tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Build Tools
        run: |
          python -m pip install build wheel setuptools
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt install python3-dev swig libssl-dev
      - name: Install skill
        run: |
          pip install ".[test]"
      - name: Run Skill Tests
        run: |
          python -m pytest test/
