name: update_skill_json
on:
  push: {}
jobs:
  update-skill-json:
    name: update_skill_json
    permissions:
      contents: write
    uses: neongeckocom/.github/.github/workflows/skill_update_json_spec.yml@master
  sync:
    name: Sync skill.json to locale
    runs-on: ubuntu-latest
    needs: update-skill-json
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Sync skill.json
        run: |
          cp skill.json locale/skill.json
      - name: Push skill.json Change
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Sync skill.json
          file_pattern: 'locale/skill.json'
          skip_dirty_check: false
          commit_author: "GitHub Actions <actions@github.com>"
