name: update_skill_json
on:
  push: {}
jobs:
  update-skill-json:
    name: update_skill_json
    permissions:
      contents: write
    uses: neongeckocom/.github/.github/workflows/skill_update_json_spec.yml@master
